echo "The name of the file is $0"
echo "The total number of arguments passed to the script = $#"
echo "The first argument is $1"
echo "The second argument is $2"
echo "The list of arguements passed is $@"
